version: '3.8'

services:
  app:
    build: ./docker
    env_file:
      - ../.env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RACK_ENV: development
    command: bin/app
#
#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_USER: dev_user
#      POSTGRES_PASSWORD: dev_pass
#      POSTGRES_DB: my_ruby_dev
#    ports:
#      - "5432:5432"
